version: "3.8"
services:
  cloudflare-ddns:
    image: realshaunoneill/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    environment:
      - CLOUDFLARE_API_KEY=
      - DNS_URL=
      - CRON_SCHEDULE=0 * * * *
