name: 'Install'
description: 'Sets up Node, and installs dependencies'

inputs:
  fetch-depth:
    default: '1'
    required: false
  persist-credentials:
    default: true
    required: false

runs:
  using: composite
  steps:
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn

    - name: Install dependencies
      shell: bash
      run: |
        corepack enable
        yarn i
