name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push x86 image
        id: build_amd
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cloudflare-ddns:latest
      -
        name: Build and push ARM image
        id: build_arm
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/arm/v7
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cloudflare-ddns:latest
      -
        name: Inspect Buildx
        run: |
          docker buildx inspect --bootstrap
