name: Quality

on:
  pull_request:
  push:
    branches:
      - 'canary'
      - 'main'
      - '*'

jobs:
  eslint:
    name: 'ESLint'
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run ESLint check
        run: npm run lint
